### model
model_name_or_path: Qwen/Qwen3-Coder-Next-Base
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: lilith_v0_2
template: qwen3_nothink
cutoff_len: 1024
max_samples: 10000
preprocessing_num_workers: null
preprocessing_batch_size: 1
dataloader_num_workers: 0
val_size: 32

### output
output_dir: saves/qwen3-coder-next/full/sft-fp8-te-smoke
logging_steps: 1
save_steps: 1000
plot_loss: false
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
max_steps: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
optim: adafactor
ddp_timeout: 180000000

### fp8
fp8: true
fp8_backend: transformer_engine
